구문오류 : 해석 단계에서 발생

예외 : 실행 단계에서 발생

#### 1. 구문오류와 예외

* 구문오류 : 잘못된 명령을 입력해 발생. 해결하기 위해선 오타나 문법적으로 필수적인 요소가 빠지진 않았는지 찾고 재코딩해야 한다.

* 예외 : 문법적인 문제가 없는데 실행 중에 예기치 않게 발생

  

#### 2. 예외 처리 방법

1. if 문을 이용한 예외의 처리 

   ```python
   print("사각형의 면적을 구해봅시다.")
   
   width = input("폭을 입력하세요: ")
   height = input("높이를 입력하세요: ")
   area = 0
   
   if width.isdigit() and height.isdigit():
       area = int(width) * int(height)
       print(area)
   else:
       print("숫자가 아닌 값이 입력되었습니다.")
       
   print("프로그램을 종료합니다.")    
   ```

2. try ~ except 문을 이용한 예외의 처리

   예외가 발생했을 때 처리

   ```python
   print("사각형의 면적을 구해봅시다.")
   
   width = input("폭을 입력하세요: ")
   height = input("높이를 입력하세요: ")
   area = 0
   
   try:
       area = int(width) * int(height)
       print(area)
   except:
       print("숫자가 아닌 값이 입력되었습니다.")
   print("프로그램을 종료합니다.")    
   ```

3. try ~ except ~ else 문을 이용한 예외의 처리

   예외가 발생했을 때 처리, 예외가 발생하지 않았을 때 처리

   ```python
   print("사각형의 면적을 구해봅시다.")
   
   width = input("폭을 입력하세요: ")
   height = input("높이를 입력하세요: ")
   area = 0
   
   try:
       area = int(width) * int(height)
       # 여기서 코드가 실행되다가 에러 발생 유무에 따라 아래로 이동한다.
   except:
       # try 부분에서 예외가 발생시 해당 블록의 코드 진행
       print("숫자가 아닌 값이 입력되었습니다.")
   else:
       # try 부분에서 예외가 발생하지 않을 시 코드 진행
       print(area)
   print("프로그램을 종료합니다.") 
   ```

4. try ~ except ~ else ~ finally 문을 이용한 예외의 처리

   예외가 발생했을 때 처리, 예외가 발생하지 않았을 때 처리, 예외 발생과 상관없이 실행

   ```python
   print("사각형의 면적을 구해봅시다.")
   
   width = input("폭을 입력하세요: ")
   height = input("높이를 입력하세요: ")
   area = 0
   
   try:
       area = int(width) * int(height)
       # 여기서 코드가 실행되다가 에러 발생 유무에 따라 아래로 이동한다.
   except:
       # try 부분에서 예외가 발생시 해당 블록의 코드 진행
       print("숫자가 아닌 값이 입력되었습니다.")
   else:
       # try 부분에서 예외가 발생하지 않을 시 코드 진행
       print(area)
   finally:
       # try 부분과 연관 없이 무조건 실행된다.
       print("finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.")
   print("프로그램을 종료합니다.") 
   ```



#### 3. 예외 객체

* 예외 객체 : 코드를 실행 중 오류가 발생하면 만들어진 것으로, 오류 발생과 관련한 정보를 가진다.

  ```python
  print("나누기 연산의 결과를 구해봅시다.")
  
  x, y, result = 0, 0, 0
  
  try:
      x = int(input("피제수를 입력하세요: "))
      y = int(input("제수를 입력하세요: "))
      result = x / y
      
  # 만약 x, y 중 하나라도 정수형 문자열이 아니라면 ValueError가 발생하므로 아래 코드 진행 
  except ValueError as ve:
      print("입력 값은 반드시 숫자를 사용해야 합니다.")
      print(type(ve), ve)  
      
  # 만약 y가 0이라면 ZeroDivisionError가 발생하므로 아래 코드 진행    
  except ZeroDivisionError as ze:
      print("제수로 0을 사용할 수 없습니다.")
      print(type(ze), ze) 
      
  # try 문에서 ValueError, ZeroDivisionError 이외의 상황이 발생 시 진행    
  except Exception as ex:
      print("예상치 못한 예외가 발생했습니다.")
      print(type(ex), ex)
  else:
      print(x, y, result) 
  finally:
      print("finally 코드 블록은 예외 발생 여부와 상관 없습니다.")
  print("프로그램을 종료합니다.")    
  ```



#### 4. 강제로 예외를 발생시키는 방법

* raise 문을 이용한 강제 예외 발생

  ```python
  def calc_area(w, h):
      if w.isdigit() and h.isdigit():
          return int(w) * int(h)
      else:
          raise ValueError("숫자가 아닌 값이 입력되었습니다.")
          # w와 h 중 하나라도 숫자형 문자열이 아닐 시 raise 함수를 통해
          # 강제로 ValueError 예외 상황을 일으킨다
  print("사각형의 면적을 구해봅시다.")
  
  width = input("폭을 입력하세요: ")
  height = input("높이를 입력하세요: ")
  
  try:
      area = calc_area(width, height)
  except ValueError as ve:
      print(type(ve), ve)
  except Exception as ex:
      print(type(ex), ex)
  else:
      print(area)
  finally:
      print("무조건 실행")
  print("프로그램을 종료합니다.")    
  ```